### PR TITLE
Updates for GHC 8.8.1 & latest safecopy

### PR DESCRIPTION
**Pull request by stepcut**
Added a couple extra class constraints and bumped the template-haskell upper bounds.

### CODE REVIEW

**Comment by larskuhtz** [comment]
What are the odds that this gets merged and released to Hackage eventually?

**Comment by kosmikus** [comment]
@larskuhtz Not too bad actually. I recall there being one issue that made me hesitate last time I looked at this. I forgot what it is. But thanks for the ping; I'll try to look again.

**Comment by kosmikus** [comment]
I remember now. I was thinking about how in principle, rather than requiring the extra `Typeable` constraints on the instance, one could implement `errorTypeName` directly, relying on `errorTypeName` for `a`. But the problem is that one would still need `Typeable ixs`, because we do not have/require `SafeCopy` instances for the index types. So all in all, I don't think it's worth it, and the approach taken in this PR is fine.

I don't think the extra constraint on `Semigroup` is needed for the `Monoid` instance. Even with `Semigroup` being a superclass of `Monoid` now, that constraint is trivially satisfied by the separate `Semigroup` instance just above. I'll merge and revert that change.

**Comment by kosmikus** [comment]
Thanks!

**Comment by kosmikus** [comment]
And released as 0.5 ...

**Comment by larskuhtz** [comment]
@kosmikus Thanks!

**Pull request merged**
